name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pytorch360convert/version.py"  # only trigger if this file changes

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: python -m pip install --upgrade pip build twine

      - name: Build distributions
        run: python -m build  # will pick up setup.py automatically

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
